import { describe, expect, it } from 'vitest';
import { buildSlugMap } from '../../domain/starlight/slug-map.js';
import { compileAutogeneratedNavigation } from './compile-autogenerated.js';

describe('compileAutogeneratedNavigation', () => {
  it('builds a complete nested sidebar with software-aware group labels', () => {
    const slugs = buildSlugMap([
      'index.md',
      'data-platform/sql/postgresql.md',
      'platform-engineering/index.md',
      'platform-engineering/runtime-systems/nodejs.md',
      'platform-engineering/service-interfaces/graphql/index.md',
      'platform-engineering/service-interfaces/graphql/schema-design.md',
      'reliability/observability/opentelemetry.md',
    ]);
    expect(slugs.ok).toBe(true);
    if (!slugs.ok) return;

    expect(compileAutogeneratedNavigation(slugs.value)).toEqual([
      { kind: 'slug', slug: '' },
      {
        kind: 'group',
        label: 'Data Platform',
        directory: 'data-platform',
        items: [
          {
            kind: 'group',
            label: 'SQL',
            directory: 'data-platform/sql',
            items: [{ kind: 'slug', slug: 'data-platform/sql/postgresql' }],
          },
        ],
      },
      {
        kind: 'group',
        label: 'Platform Engineering',
        directory: 'platform-engineering',
        items: [
          { kind: 'slug', slug: 'platform-engineering' },
          {
            kind: 'group',
            label: 'Runtime Systems',
            directory: 'platform-engineering/runtime-systems',
            items: [{ kind: 'slug', slug: 'platform-engineering/runtime-systems/nodejs' }],
          },
          {
            kind: 'group',
            label: 'Service Interfaces',
            directory: 'platform-engineering/service-interfaces',
            items: [
              {
                kind: 'group',
                label: 'GraphQL',
                directory: 'platform-engineering/service-interfaces/graphql',
                items: [
                  { kind: 'slug', slug: 'platform-engineering/service-interfaces/graphql' },
                  {
                    kind: 'slug',
                    slug: 'platform-engineering/service-interfaces/graphql/schema-design',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        kind: 'group',
        label: 'Reliability',
        directory: 'reliability',
        items: [
          {
            kind: 'group',
            label: 'Observability',
            directory: 'reliability/observability',
            items: [{ kind: 'slug', slug: 'reliability/observability/opentelemetry' }],
          },
        ],
      },
    ]);
  });

  it('retains original directory casing that slug generation removes', () => {
    const slugs = buildSlugMap(['SDKTools/GraphQL/page.md']);
    expect(slugs.ok).toBe(true);
    if (!slugs.ok) return;

    expect(compileAutogeneratedNavigation(slugs.value)).toMatchObject([
      {
        label: 'SDKTools',
        directory: 'SDKTools',
        items: [{ label: 'GraphQL', directory: 'SDKTools/GraphQL' }],
      },
    ]);
  });

  it('aligns source directories after a synthetic locale prefix', () => {
    const slugs = buildSlugMap(['guides/intro.fr.md'], {
      pathTransform: () => 'fr/guides/intro.md',
    });
    expect(slugs.ok).toBe(true);
    if (!slugs.ok) return;

    expect(compileAutogeneratedNavigation(slugs.value)).toMatchObject([
      {
        label: 'Fr',
        directory: 'fr',
        items: [{ label: 'Guides', directory: 'guides' }],
      },
    ]);
  });
});
