/**
 * Build an explicit Starlight sidebar tree when MkDocs has no `nav:`.
 *
 * Starlight's all-pages fallback derives nested group labels from directory
 * names. Most documentation directories are lowercase slugs, so group labels
 * lose their headline and product casing. An explicit tree
 * lets page links continue to inherit their frontmatter titles while giving
 * every directory group a readable, software-aware label.
 */

import type { SidebarEntry } from '../../domain/starlight/sidebar.js';
import type { SlugMap } from '../../domain/starlight/slug-map.js';
import { humanizeSidebarLabel } from './humanize-sidebar-label.js';

interface MutableDirectory {
  readonly segment: string;
  readonly pages: Array<{
    readonly slug: string;
    readonly sourcePath: string;
    readonly index: boolean;
  }>;
  readonly children: Map<string, MutableDirectory>;
}

export function compileAutogeneratedNavigation(slugMap: SlugMap): ReadonlyArray<SidebarEntry> {
  const labelSegments = collectOriginalDirectorySegments(slugMap);
  const root = createDirectory('');

  for (const record of slugMap.entries()) {
    const slugSegments = splitPath(record.slug);
    const index = isDirectoryIndex(record.sourcePath);
    const directorySegments = index ? slugSegments : slugSegments.slice(0, -1);
    const directory = ensureDirectory(root, directorySegments);
    directory.pages.push({ slug: record.slug, sourcePath: record.sourcePath, index });
  }

  return renderDirectory(root, '', labelSegments);
}

function createDirectory(segment: string): MutableDirectory {
  return { segment, pages: [], children: new Map() };
}

function ensureDirectory(
  root: MutableDirectory,
  segments: ReadonlyArray<string>,
): MutableDirectory {
  let cursor = root;
  for (const segment of segments) {
    let child = cursor.children.get(segment);
    if (child === undefined) {
      child = createDirectory(segment);
      cursor.children.set(segment, child);
    }
    cursor = child;
  }
  return cursor;
}

function renderDirectory(
  directory: MutableDirectory,
  parentPath: string,
  labelSegments: ReadonlyMap<string, string>,
): ReadonlyArray<SidebarEntry> {
  const entries: SidebarEntry[] = [];

  for (const page of [...directory.pages].sort(comparePages)) {
    entries.push({ kind: 'slug', slug: page.slug });
  }

  const children = [...directory.children.values()].sort((a, b) =>
    a.segment.localeCompare(b.segment, 'en'),
  );
  for (const child of children) {
    const directoryPath = parentPath === '' ? child.segment : `${parentPath}/${child.segment}`;
    const sourceSegment = labelSegments.get(directoryPath) ?? child.segment;
    entries.push({
      kind: 'group',
      label: humanizeSidebarLabel(sourceSegment),
      items: renderDirectory(child, directoryPath, labelSegments),
    });
  }

  return entries;
}

function comparePages(
  left: { readonly slug: string; readonly sourcePath: string; readonly index: boolean },
  right: { readonly slug: string; readonly sourcePath: string; readonly index: boolean },
): number {
  if (left.index !== right.index) return left.index ? -1 : 1;
  return left.sourcePath.localeCompare(right.sourcePath, 'en');
}

/**
 * Slugs are lowercased by Astro, but source directories may carry meaningful
 * casing. Align source and slug directories from the right so static-i18n's
 * synthetic locale prefix does not throw off the correspondence.
 */
function collectOriginalDirectorySegments(slugMap: SlugMap): ReadonlyMap<string, string> {
  const out = new Map<string, string>();
  for (const record of slugMap.entries()) {
    const sourceParts = splitPath(record.sourcePath);
    const sourceDirectories = sourceParts.slice(0, -1);
    const slugParts = splitPath(record.slug);
    const slugDirectories = isDirectoryIndex(record.sourcePath)
      ? slugParts
      : slugParts.slice(0, -1);
    const offset = slugDirectories.length - sourceDirectories.length;
    for (let sourceIndex = 0; sourceIndex < sourceDirectories.length; sourceIndex += 1) {
      const slugIndex = sourceIndex + offset;
      const sourceSegment = sourceDirectories[sourceIndex];
      if (slugIndex < 0 || sourceSegment === undefined) continue;
      const directoryPath = slugDirectories.slice(0, slugIndex + 1).join('/');
      if (directoryPath.length > 0 && !out.has(directoryPath)) {
        out.set(directoryPath, sourceSegment);
      }
    }
  }
  return out;
}

function isDirectoryIndex(sourcePath: string): boolean {
  const filename = splitPath(sourcePath).at(-1);
  return filename === 'index.md' || filename === 'index.mdx' || filename === 'README.md';
}

function splitPath(path: string): ReadonlyArray<string> {
  if (path.length === 0) return [];
  return path.replace(/\\/g, '/').split('/').filter(Boolean);
}
