/**
 * Turn a filesystem directory segment into a readable sidebar group label.
 *
 * Generic title-casing is not enough for software documentation: it mangles
 * acronyms, product names, and platform names. Keep the casing
 * table local and deterministic instead of adding a runtime dependency whose
 * general-purpose dictionary will not understand technology brands.
 *
 * This is intentionally used only for labels synthesized from paths. Titles
 * authored in `nav:` or `.pages` remain untouched.
 */

const PHRASE_CASING: Readonly<Record<string, string>> = {
  aspnet: 'ASP.NET',
  'c-plus-plus': 'C++',
  'c-sharp': 'C#',
  cpp: 'C++',
  csharp: 'C#',
  'ci-cd': 'CI/CD',
  cicd: 'CI/CD',
  'dot-net': '.NET',
  dotnet: '.NET',
  'f-sharp': 'F#',
  fsharp: 'F#',
  'next-js': 'Next.js',
  nextjs: 'Next.js',
  'node-js': 'Node.js',
  nodejs: 'Node.js',
  'nuxt-js': 'Nuxt.js',
  nuxtjs: 'Nuxt.js',
  'objective-c': 'Objective-C',
  objectivec: 'Objective-C',
  'react-js': 'React',
  reactjs: 'React',
  'vue-js': 'Vue.js',
  vuejs: 'Vue.js',
};

// Common language and data-format spellings are validated against GitHub
// Linguist's maintained `lib/linguist/languages.yml` catalog. Linguist covers
// 800+ canonical names and aliases; this path-label subset focuses on terms
// likely to appear as documentation directory names.
const TERM_CASING: Readonly<Record<string, string>> = {
  a11y: 'A11y',
  abap: 'ABAP',
  abnf: 'ABNF',
  ai: 'AI',
  antlr: 'ANTLR',
  api: 'API',
  apis: 'APIs',
  aws: 'AWS',
  basic: 'BASIC',
  bibtex: 'BibTeX',
  cd: 'CD',
  cdk: 'CDK',
  cli: 'CLI',
  clis: 'CLIs',
  cncf: 'CNCF',
  cmake: 'CMake',
  cobol: 'COBOL',
  coffeescript: 'CoffeeScript',
  cpu: 'CPU',
  css: 'CSS',
  cql: 'CQL',
  csv: 'CSV',
  cuda: 'CUDA',
  db: 'DB',
  dba: 'DBA',
  devcontainer: 'Dev Container',
  devcontainers: 'Dev Containers',
  devops: 'DevOps',
  devsecops: 'DevSecOps',
  dns: 'DNS',
  ec2: 'EC2',
  ecr: 'ECR',
  ecs: 'ECS',
  eks: 'EKS',
  faq: 'FAQ',
  faqs: 'FAQs',
  faas: 'FaaS',
  gcp: 'GCP',
  git: 'Git',
  github: 'GitHub',
  gitlab: 'GitLab',
  gitops: 'GitOps',
  gpu: 'GPU',
  graphql: 'GraphQL',
  grpc: 'gRPC',
  hcl: 'HCL',
  hlsl: 'HLSL',
  html: 'HTML',
  http: 'HTTP',
  https: 'HTTPS',
  i18n: 'i18n',
  iaas: 'IaaS',
  iac: 'IaC',
  iam: 'IAM',
  ide: 'IDE',
  ides: 'IDEs',
  ios: 'iOS',
  ip: 'IP',
  ipados: 'iPadOS',
  ipv4: 'IPv4',
  ipv6: 'IPv6',
  js: 'JS',
  javascript: 'JavaScript',
  json: 'JSON',
  json5: 'JSON5',
  jsx: 'JSX',
  jwt: 'JWT',
  k8s: 'K8s',
  l10n: 'L10n',
  ldap: 'LDAP',
  llm: 'LLM',
  llms: 'LLMs',
  llvm: 'LLVM',
  macos: 'macOS',
  md: 'MD',
  mdx: 'MDX',
  mkdocs: 'MkDocs',
  ml: 'ML',
  mlops: 'MLOps',
  mssql: 'Microsoft SQL Server',
  mysql: 'MySQL',
  nosql: 'NoSQL',
  npm: 'npm',
  numpy: 'NumPy',
  oauth: 'OAuth',
  oidc: 'OIDC',
  openapi: 'OpenAPI',
  opencl: 'OpenCL',
  opentelemetry: 'OpenTelemetry',
  paas: 'PaaS',
  pdf: 'PDF',
  php: 'PHP',
  plsql: 'PLSQL',
  pnpm: 'pnpm',
  postgresql: 'PostgreSQL',
  postgres: 'Postgres',
  postcss: 'PostCSS',
  powershell: 'PowerShell',
  protobuf: 'Protocol Buffers',
  qml: 'QML',
  raml: 'RAML',
  rbac: 'RBAC',
  rds: 'RDS',
  rest: 'REST',
  rpc: 'RPC',
  s3: 'S3',
  saas: 'SaaS',
  saml: 'SAML',
  sdk: 'SDK',
  sdks: 'SDKs',
  seo: 'SEO',
  sftp: 'SFTP',
  shellcheck: 'ShellCheck',
  sql: 'SQL',
  sqlite: 'SQLite',
  sre: 'SRE',
  sso: 'SSO',
  ssh: 'SSH',
  ssl: 'SSL',
  tcp: 'TCP',
  tls: 'TLS',
  toml: 'TOML',
  ts: 'TS',
  tsx: 'TSX',
  tvos: 'tvOS',
  typescript: 'TypeScript',
  typespec: 'TypeSpec',
  udp: 'UDP',
  ui: 'UI',
  unix: 'Unix',
  uri: 'URI',
  uris: 'URIs',
  url: 'URL',
  urls: 'URLs',
  utf8: 'UTF-8',
  ux: 'UX',
  vm: 'VM',
  vms: 'VMs',
  vpc: 'VPC',
  vpcs: 'VPCs',
  vpn: 'VPN',
  vpns: 'VPNs',
  vscode: 'VS Code',
  vue: 'Vue.js',
  wasm: 'WebAssembly',
  watchos: 'watchOS',
  websocket: 'WebSocket',
  websockets: 'WebSockets',
  webassembly: 'WebAssembly',
  webidl: 'WebIDL',
  webvtt: 'WebVTT',
  xml: 'XML',
  xquery: 'XQuery',
  xslt: 'XSLT',
  yaml: 'YAML',
  yml: 'YAML',
};

const LOWERCASE_MIDDLE_WORDS = new Set([
  'a',
  'an',
  'and',
  'as',
  'at',
  'but',
  'by',
  'for',
  'from',
  'in',
  'into',
  'nor',
  'of',
  'on',
  'onto',
  'or',
  'over',
  'per',
  'the',
  'to',
  'up',
  'via',
  'vs',
  'with',
]);

export function humanizeSidebarLabel(segment: string): string {
  const trimmed = segment.trim();
  if (trimmed.length === 0) return trimmed;

  const phraseKey = trimmed.toLowerCase();
  const phrase = PHRASE_CASING[phraseKey];
  if (phrase !== undefined) return phrase;

  const words = trimmed.split(/[-_\s]+/).filter((word) => word.length > 0);
  return words
    .map((word, index) => {
      const key = word.toLowerCase();
      const technologyPhrase = PHRASE_CASING[key];
      if (technologyPhrase !== undefined) return technologyPhrase;
      const technologyTerm = TERM_CASING[key];
      if (technologyTerm !== undefined) return technologyTerm;
      if (index > 0 && index < words.length - 1 && LOWERCASE_MIDDLE_WORDS.has(key)) {
        return key;
      }
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
}
