/**
 * Produce the CSS shim shipped alongside converted Starlight projects.
 *
 * Pure: takes an optional Starlight palette derived from the source MkDocs
 * Material `theme.palette`, returns the stylesheet text. The interface API
 * writes the result to `outputDir/src/styles/mkdocs-migration.css`.
 *
 * The styles cover the four CSS classes the AST transformers emit:
 *   .sl-card-grid  — wrapper for card grids (display: grid)
 *   .sl-card       — individual card (light bordering, padding)
 *   .sl-grid       — generic grid wrapper
 *   .sl-tabs       — tab container
 *   .sl-tab        — individual tab pane (with data-label-driven button)
 *
 * When a palette is supplied, a `:root` block is appended with `--sl-hue-*`
 * overrides translating Material's primary color into Starlight's accent
 * ramp. The visual rules are intentionally minimal — users can override or
 * extend them in their own `src/styles/`.
 */

import type { StarlightPalette } from '../../domain/starlight/palette-mapping.js';
import type { MaterialFontConfig } from '../../domain/starlight/font-mapping.js';

const STYLESHEET = `/*
 * mkdocs-to-starlight migration shim.
 * Generated by the converter; safe to edit. Provides minimal styles for
 * the .sl-card-grid, .sl-card, .sl-grid, .sl-tabs, .sl-tab classes emitted
 * by the AST transformers when converting MkDocs Material constructs.
 */

.sl-card-grid {
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));
  margin-block: 1.5rem;
}

.sl-card {
  border: 1px solid var(--sl-color-hairline, #e5e5e5);
  border-radius: 0.5rem;
  padding: 1rem 1.25rem;
}

.sl-card > strong {
  display: block;
  font-size: 1.05rem;
  margin-bottom: 0.25rem;
}

.sl-grid {
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));
  margin-block: 1.5rem;
}

.sl-tabs {
  border: 1px solid var(--sl-color-hairline, #e5e5e5);
  border-radius: 0.5rem;
  margin-block: 1.5rem;
  overflow: hidden;
}

.sl-tab {
  padding: 1rem 1.25rem;
  border-top: 1px solid var(--sl-color-hairline, #e5e5e5);
}

.sl-tab:first-child {
  border-top: none;
}

.sl-tab[data-label]::before {
  content: attr(data-label);
  display: block;
  font-weight: 600;
  margin-bottom: 0.5rem;
  color: var(--sl-color-accent, #0070f3);
}
`;

export type PaletteStrategy = 'translate' | 'skip' | 'custom';

export function serializeStyleSheet(
  palette?: StarlightPalette | null,
  fonts?: MaterialFontConfig | null,
  paletteStrategy?: PaletteStrategy,
): string {
  let out = STYLESHEET;
  const skipAccent = paletteStrategy === 'skip' || paletteStrategy === 'custom';
  if (!skipAccent && palette !== undefined && palette !== null && !palette.isCustom) {
    out += buildPaletteOverride(palette);
  }
  if (fonts !== undefined && fonts !== null) {
    out += buildFontOverride(fonts);
  }
  return out;
}

function buildFontOverride(fonts: MaterialFontConfig): string {
  const lines: string[] = [];
  if (fonts.text !== undefined) {
    lines.push(`  --sl-font: '${fonts.text.family}';`);
  }
  if (fonts.code !== undefined) {
    lines.push(`  --sl-font-mono: '${fonts.code.family}';`);
  }
  if (lines.length === 0) return '';
  return `\n/* Translated from MkDocs Material \`theme.font\`. */\n:root {\n${lines.join('\n')}\n}\n`;
}

function buildPaletteOverride(palette: StarlightPalette): string {
  const lightHue = String(palette.accentHue);
  const lightChroma = palette.accentChroma.toFixed(2);
  const darkHue =
    palette.darkAccentHue === undefined ? lightHue : String(palette.darkAccentHue);
  const darkChroma =
    palette.darkAccentChroma === undefined
      ? lightChroma
      : palette.darkAccentChroma.toFixed(2);
  const sourceComment =
    palette.darkSourceName === undefined
      ? `\`theme.palette.primary: ${palette.sourceName}\``
      : `\`theme.palette\` (default: ${palette.sourceName}, slate: ${palette.darkSourceName})`;
  return `\n/* Translated from MkDocs Material ${sourceComment}. */\n:root {\n  --sl-hue-accent: ${lightHue};\n  --sl-color-accent-low: oklch(0.92 ${lightChroma} ${lightHue});\n  --sl-color-accent: oklch(0.6 ${lightChroma} ${lightHue});\n  --sl-color-accent-high: oklch(0.4 ${lightChroma} ${lightHue});\n}\n[data-theme='dark'] {\n  --sl-hue-accent: ${darkHue};\n  --sl-color-accent-low: oklch(0.32 ${darkChroma} ${darkHue});\n  --sl-color-accent: oklch(0.7 ${darkChroma} ${darkHue});\n  --sl-color-accent-high: oklch(0.92 ${darkChroma} ${darkHue});\n}\n`;
}
