/**
 * Single source of truth for every dependency version the converter pins
 * into a generated `package.json`.
 *
 * Why this file exists: every entry here gets baked into a real user's
 * project. If they sit untouched for a year, every fresh conversion
 * installs a stale set of packages and generates `ERESOLVE` errors when
 * peer-dep ranges drift. Centralising them here means one obvious place
 * to look during a periodic refresh, and a single git diff per refresh.
 *
 * The two-part structure (`CORE_VERSIONS` + `FEATURE_DEPENDENCIES`) is
 * deliberate: the core block always ships, the feature block only adds
 * entries when the corresponding feature is detected in the source. Keep
 * them apart so the impact of a version bump is local.
 */

/**
 * Stable identifier for a feature whose presence in the source pulls
 * extra dependencies into the generated `package.json`. Each value
 * matches a `featureId` in the conversion-mapping table so the
 * registration stays auditable from one place.
 */
export type DetectedFeature =
  | 'math'
  | 'mermaid'
  | 'image-zoom'
  | 'versions'
  | 'blog'
  | 'tags'
  | 'last-updated'
  | 'rss'
  | 'package-managers'
  | 'swagger-ui'
  | 'kbd'
  | 'github-alerts'
  | 'announcement'
  | 'page-actions'
  | 'og-cards'
  | 'heading-badges'
  | 'sidebar-topics'
  | 'scroll-to-top'
  | 'giscus'
  | 'markdown-blocks'
  | 'd2'
  | 'auto-drafts'
  | 'base-path';

export const CORE_VERSIONS = {
  // Astro 7 and the current Starlight plugin line require Node 22.12+.
  // Emit this into generated package.json files so unsupported runtimes fail
  // at install time with a clear engine message instead of during a build.
  node: '>=22.12.0',
  // Pinned to 0.41.7+:
  //   - 0.30/0.31 had a sidebar slug-resolution bug (rejected every
  //     `{ slug: 'foo' }` entry); fixed in 0.34.
  //   - 0.39.0 (2026-05-07) reshaped autogenerated sidebar groups: the
  //     legacy `{ label, autogenerate }` form is rejected; the new
  //     `{ label, items: [{ autogenerate: { directory, collapsed? } }] }`
  //     form is mandatory. Our serializer emits the new shape.
  //   - 0.39.1 added 13 built-in icons (clock, padlock, database, server,
  //     code-branch, question, question-circle, desktop, mobile-android,
  //     window, notes, analytics, solidjs) that the curated icon map now
  //     references; a pin <0.39.1 resolves to icons that do not exist.
  //   - 0.41.0 is the Astro 7 release (peers `astro@^7.0.2`, drops Astro 6)
  //     and the peer floor for several companion plugins at their current
  //     pins (links-validator 0.25, blog 0.28, github-alerts 0.4,
  //     heading-badges 0.8, image-zoom 0.15, llms-txt 0.11 → `>=0.41.0`).
  //     The Astro-6-era `@astrojs/markdown-satteri` peer is gone; 0.41
  //     instead peers `@astrojs/markdown-remark@^7.2.0` (npm auto-installs
  //     it) — Sätteri became Astro 7's built-in default processor.
  //   - Patch floor 0.41.7: 0.41.1 fixed a dependency-resolution issue
  //     introduced in 0.41.0, and 0.41.4 fixed `docsSchema({ extend })`
  //     with Zod enums — our generated `content.config.ts` uses `extend`
  //     whenever source frontmatter has fields outside `docsSchema()`.
  // Under npm's `^0.y.z` rule, `^0.41.7` resolves to `>=0.41.7 <0.42.0`.
  starlight: '^0.41.7',
  // Latest Astro 7 patch; satisfies Starlight 0.41's `astro@^7.0.2` peer
  // (both resolve inside `>=7.x <8.0.0`). Starlight pins the major Astro
  // version; a major mismatch raises `ERESOLVE` on install. The previous
  // refresh held the stack on Astro 6 because no Starlight release
  // supported Astro 7; Starlight 0.41.0 lifted that — the whole stack now
  // rides Astro 7.
  astro: '^7.2.0',
  // Biome 2.3+ supports `.astro` (HTML/CSS/JS/TS sub-blocks) plus the
  // rest of the Astro/Starlight scaffold (.mjs, .ts, .json, .css). Baked
  // in as a devDep so `npm run format` works the moment users
  // `npm install`. Markdown/MDX is intentionally NOT formatted by Biome
  // — those go through remark-stringify in the converter.
  biome: '^2.5.7',
  // `astro check` hard-requires these two. Without them a fresh project
  // renders an interactive "npm i @astrojs/check typescript — Continue?"
  // prompt, which under the converter's own `--check` pass (piped,
  // non-interactive stdio) waited invisibly until the full timeout —
  // every fresh `--check` run burned 10 minutes and misreported a
  // language-server hang (field-tested 2026-07-23). Baking them in makes
  // `--check` and a user's own `npx astro check` work on first install.
  astroCheck: '^0.9.10',
  // @astrojs/check 0.9.10 peers `typescript ^5.0.0 || ^6.0.0` — pinning
  // the ^7 line would ERESOLVE. Hold at ^6 until the peer broadens.
  typescript: '^6.0.0',
  // NOTE: no `sharp` pin. Astro 7 depends on sharp directly
  // (`^0.34.0 || ^0.35.0`), so the previously emitted top-level pin was
  // vestigial — pure maintenance surface that could force a second native
  // sharp build whenever astro's accepted range moved first.
  //
  // Fontsource packages (from Material `theme.font` → `@fontsource/<family>`)
  // all sit on the same major line. Pinned here instead of the literal
  // `latest` previously emitted — the one unpinned dep in generated
  // projects; a Fontsource major with changed CSS paths would break the
  // emitted `customCss` imports on fresh installs.
  fontsource: '^5.3.0',
  // Default-on link-validation plugin, run on every build.
  // (0.25.2 peers `@astrojs/starlight >=0.41.0`, `astro >=7.0.2`.)
  starlightLinksValidator: '^0.25.2',
  // Default-on AI-assistant accessibility — generates llms.txt /
  // llms-full.txt / llms-small.txt automatically from Starlight content
  // with no per-site config needed. (0.11.0 peers `astro ^7.0.0`; the
  // previous 0.10.0 peered `astro ^6.0.0`, which ERESOLVEs against the
  // Astro 7 core — this bump is required, not cosmetic.)
  starlightLlmsTxt: '^0.11.0',
  // NOT bundled: `starlight-md-txt` (raw Markdown at `.md.txt` URLs) was
  // evaluated 2026-07-23 as a default-on llms-txt companion and rejected —
  // 0.1.0 re-renders page content through an MDX-flavored pipeline that
  // crashes on HTML comments ("Unexpected character `!` before name"),
  // and every Material blog post carries `<!-- more -->` as its excerpt
  // marker. Re-evaluate when a release parses plain Markdown.
} as const;

/**
 * Feature-specific dependency lists. Each detected feature maps to zero
 * or more `[name, version]` pairs that get added to the generated
 * `package.json`'s `dependencies` block.
 */
export const FEATURE_DEPENDENCIES: Readonly<
  Record<DetectedFeature, ReadonlyArray<readonly [string, string]>>
> = {
  math: [
    ['remark-math', '^6.0.0'],
    ['rehype-katex', '^7.0.1'],
    // Pin `katex` directly so the `katex/dist/katex.min.css` import that
    // astro.config wires into customCss resolves on a fresh install.
    // rehype-katex pulls it in transitively, but pinning makes the path
    // stable across version bumps. Caveat: rehype-katex renders with its
    // own bundled katex (`^0.16`), so the stylesheet here can be ahead of
    // the markup generator — no reported breakage across this gap, but if
    // formulas ever style oddly, aligning this pin to rehype-katex's
    // bundled major is the first thing to try.
    ['katex', '^0.18.4'],
    // Astro 7 made Sätteri the default Markdown processor; remark/rehype
    // plugins only run when astro.config sets `markdown.processor:
    // unified(...)` imported from `@astrojs/markdown-remark` (see
    // `astro-config.ts`). Starlight 0.41 already peers `^7.2.0`, so the
    // package lands either way — pin it directly because the generated
    // config imports it by name.
    ['@astrojs/markdown-remark', '^7.2.2'],
  ],
  // astro-mermaid 2.x peers `astro >=4` and requires `mermaid ^10 || ^11`.
  // Pin Mermaid directly because strict package managers such as pnpm do not
  // guarantee a root-level peer link for astro-mermaid's generated import.
  // `@mermaid-js/layout-elk` is optional and is not needed by the default
  // renderer. `^1.0.0` could not reach the 2.x line.
  mermaid: [
    ['astro-mermaid', '^2.1.0'],
    ['mermaid', '^11.16.1'],
  ],
  // 0.15.0 peers `@astrojs/starlight >=0.41.0`, matching the core pin.
  'image-zoom': [['starlight-image-zoom', '^0.15.0']],
  // `mike` (versioned docs) → `starlight-versions`.
  versions: [
    // starlight-versions 0.9.x peers `@astrojs/starlight >=0.39.0`; `^0.8.0`
    // could not reach it.
    ['starlight-versions', '^0.9.1'],
    // NOT bundled: `starlight-changelogs@0.5.1` (still current on
    // 2026-08-10) depends on `@ascorbic/loader-utils@1`, whose Astro peer
    // stops at v5. npm therefore installs a second `astro@5.18.2` tree next
    // to the generated Astro 7 stack. That tree carries high-severity Astro
    // and sharp advisories, and the plugin itself now requires Node 22.12.
    // Re-evaluate when loader-utils supports Astro 7 and the nested runtime
    // disappears. Version switching remains fully covered by
    // `starlight-versions`; changelogs were only an optional companion.
  ],
  // 0.27.0 is the Astro 7 support release (peers Starlight >=0.41); older
  // lines target the removed Astro 6 Markdown pipeline. 0.28.0 adds
  // multi-instance blogs and structured data with no config breaks.
  blog: [['starlight-blog', '^0.28.0']],
  tags: [['starlight-tags', '^1.0.1']],
  // last-updated is a Starlight built-in (`lastUpdated: true`) — no extra deps.
  'last-updated': [],
  rss: [['@astrojs/rss', '^4.0.19']],
  'package-managers': [['starlight-package-managers', '^0.12.0']],
  // Hold at 0.24.x even though 0.26.0 is current. Both 0.25 and 0.26 add
  // `httpsnippet@^3.0.10`, which pins vulnerable `form-data@4.0.4` exactly
  // (GHSA-hmw2-7cc7-3qxx), leaving no safe semver resolution or upstream
  // audit fix. 0.24.0 peers `astro >=6`, Starlight >=0.38, and
  // `@astrojs/markdown-remark >=7`, so it remains compatible with this
  // Astro 7 stack without the vulnerable dependency. Re-evaluate when
  // httpsnippet releases a form-data >=4.0.6 pin or starlight-openapi drops it.
  'swagger-ui': [['starlight-openapi', '^0.24.0']],
  // pymdownx.keys (`++ctrl+alt+del++`) → starlight-kbd. The plugin
  // styles plain `<kbd>` tags via injected CSS so existing emitted HTML
  // keeps working — installing the dep is the value-add.
  kbd: [['starlight-kbd', '^0.4.0']],
  // GitHub-style `> [!NOTE]` blockquote alerts → starlight-github-alerts.
  // Detected from source scan; the plugin transforms the alert syntax
  // into Starlight asides at build time. 0.4.0 peers
  // `@astrojs/starlight >=0.41.0`, which our core pin now satisfies; the
  // older `^0.3.0` pin paired with the previous Starlight 0.40 floor.
  'github-alerts': [['starlight-github-alerts', '^0.4.0']],
  // Material `theme.features: [announce.dismiss]` (Insiders flag) →
  // starlight-announcement. Provides dismissible banners with optional
  // scheduling.
  announcement: [['starlight-announcement', '^1.1.0']],
  // Material `theme.features: [content.action.view]` →
  // starlight-page-actions. Adds page-action buttons (View source, etc.).
  'page-actions': [['starlight-page-actions', '^0.7.0']],
  // Material `social` plugin (per-page OG card PNGs) → astro-og-canvas.
  // The canonical Starlight pattern (HiDeoo guides, 2026) is to mount
  // an Astro endpoint that calls `OGImageRoute` from astro-og-canvas.
  // Distinct from Starlight's `social: []` header config.
  //
  // 0.13.0 is required on Astro 7: 0.11.x peers `astro ^5.0.0 ||
  // ^6.0.0-alpha` (ERESOLVE against astro 7); 0.12.0 added Astro 7
  // support; 0.13.0 removed `OGImageRoute`'s `param` option (the route
  // param is now auto-detected from the endpoint filename — the emitted
  // endpoint in `og-endpoint.ts` no longer passes it).
  'og-cards': [['astro-og-canvas', '^0.13.0']],
  // ATX headings with `attr_list` classes (`## Title { .badge }`)
  // detected by `scan-heading-badges` → `starlight-heading-badges`. The
  // plugin renders the class as an inline Badge next to the heading
  // text, recreating Material's heading-badge idiom.
  'heading-badges': [['starlight-heading-badges', '^0.8.0']],
  // Material `theme.features: [navigation.tabs]` → starlight-sidebar-topics.
  // Top-level nav sections become topics with per-topic sidebars, mirroring
  // Material's header tabs. Opt-out via `--no-sidebar-topics`.
  'sidebar-topics': [['starlight-sidebar-topics', '^0.8.0']],
  // Material `theme.features: [navigation.top]` (back-to-top button) →
  // starlight-scroll-to-top. Zero-config.
  'scroll-to-top': [['starlight-scroll-to-top', '^1.0.1']],
  // Material comments via a Giscus script in `overrides/partials/
  // comments.html` → starlight-giscus. Only auto-installed when the
  // partial exists AND its data-repo/data-repo-id/data-category/
  // data-category-id attributes parse — the plugin hard-requires all four.
  // (1.1.0 peers `@astrojs/starlight >=0.41.0`.)
  giscus: [['starlight-giscus', '^1.1.0']],
  // Material admonition types beyond Starlight's four asides are handled by
  // a local generated remark plugin. Pin its direct imports instead of
  // starlight-markdown-blocks, whose current release configures Astro through
  // the deprecated top-level markdown.remarkPlugins option.
  'markdown-blocks': [
    ['@astrojs/markdown-remark', '^7.2.2'],
    ['unist-util-visit', '^5.1.0'],
  ],
  // mkdocs-d2-plugin (D2 diagrams) → astro-d2 (0.13.1 peers `astro
  // >=7.0.0`). NOTE: astro-d2 shells out to the `d2` CLI at build time;
  // the config emission includes that caveat as a comment. There is no
  // astro-plantuml equivalent entry: astro-plantuml 0.1.4 still peers
  // `astro ^5.5.6`, which ERESOLVEs against this stack — it stays a
  // recommendation diagnostic until upstream broadens the peer.
  d2: [['astro-d2', '^0.13.1']],
  // MkDocs 1.6 `draft_docs` path matches are rewritten to `draft: true`.
  // This plugin keeps those pages visible (and labeled) during development,
  // then removes explicit sidebar links to them from production builds.
  // 0.3.0 peers Starlight >=0.38 and requires Node >=22.12, the same Node
  // floor as the generated Astro 7 stack.
  'auto-drafts': [['starlight-auto-drafts', '^0.3.0']],
  // `site_url` with a subpath (GitHub Pages project sites) → Astro `base:`
  // plus starlight-base-path, which prefixes content links with the base
  // automatically. (0.2.1 peers `astro >=6`, `@astrojs/starlight >=0.38`,
  // `@astrojs/markdown-remark >=7` — all satisfied by the core pins.)
  'base-path': [['starlight-base-path', '^0.2.1']],
};
