/**
 * Typed shape of a Starlight sidebar configuration entry.
 *
 * Mirrors the four canonical Starlight sidebar entry types:
 *   - SlugEntry   — references a docs page by slug, optionally with a label
 *   - LinkEntry   — external or non-docs URL with required label
 *   - GroupEntry  — manual group { label, items }
 *   - AutoEntry   — autogenerated group { label, autogenerate: { directory } }
 *
 * Pure types — the navigation compiler emits these and the infrastructure
 * layer serializes them into `astro.config.mjs`.
 */

export type SidebarEntry = SlugEntry | LinkEntry | GroupEntry | AutoEntry;

export interface SlugEntry {
  readonly kind: 'slug';
  readonly slug: string;
  readonly label?: string;
}

export interface LinkEntry {
  readonly kind: 'link';
  readonly label: string;
  readonly href: string;
}

export interface GroupEntry {
  readonly kind: 'group';
  readonly label: string;
  readonly items: ReadonlyArray<SidebarEntry>;
  readonly collapsed?: boolean;
}

export interface AutoEntry {
  readonly kind: 'auto';
  readonly label: string;
  readonly directory: string;
  readonly collapsed?: boolean;
}
