/**
 * Curated mapping from Material/FontAwesome/Octicons/Simple-Icons shortcodes
 * to Starlight built-in icon names. Pure data — no logic.
 *
 * Starlight ships ~250 built-in icons across UI, brand, and tech-logo
 * categories; Material ships 10,000+ icons. Mapping every Material icon is
 * neither possible nor useful. This table covers the ~250 high-frequency
 * shortcodes that appear in real-world MkDocs Material docs (per the
 * research corpus): card grids, navigation, feature blocks, and the social
 * link sets configured under `extra.social[]`.
 *
 * Anything outside the table falls through to the SVG-package adapter
 * (kind: 'local-svg') which copies the original SVG asset into the
 * Starlight project's `src/icons/` directory. Users can override or extend
 * this map via the converter's config; their overrides win against the
 * curated table.
 *
 * Coverage notes:
 *   - Material UI vocabulary: alert/check/close/etc. → closest Starlight
 *     name (sometimes 1:1, sometimes approximate — Starlight's set is the
 *     ground truth).
 *   - Brand logos use Starlight's social-icon vocabulary.
 *   - Tech logos use Starlight's icon-set vocabulary (astro, vscode, npm,
 *     node, github, gitlab, ...).
 */

export const CURATED_ICON_MAP: Readonly<Record<string, string>> = {
  // --- Material — UI / general ---
  'material-cog': 'setting',
  'material-cog-outline': 'setting',
  'material-account': 'user',
  'material-account-circle': 'user',
  'material-account-multiple': 'user',
  'material-rocket': 'rocket',
  'material-rocket-launch': 'rocket',
  'material-star': 'star',
  'material-star-outline': 'star',
  'material-heart': 'heart',
  'material-heart-outline': 'heart',
  'material-magnify': 'magnifier',
  'material-magnify-plus': 'magnifier',
  'material-download': 'cloud-download',
  'material-cloud-download': 'cloud-download',
  'material-upload': 'cloud-upload',
  'material-cloud-upload': 'cloud-upload',
  'material-link': 'external',
  'material-link-variant': 'external',
  'material-open-in-new': 'external',
  'material-pencil': 'pencil',
  'material-pencil-outline': 'pencil',
  'material-book': 'document',
  'material-book-open': 'open-book',
  'material-book-open-variant': 'open-book',
  'material-information': 'information',
  'material-information-outline': 'information',
  'material-information-variant': 'information',
  'material-check': 'approve-check',
  'material-check-circle': 'approve-check-circle',
  'material-check-circle-outline': 'approve-check-circle',
  'material-check-bold': 'approve-check',
  'material-close': 'close',
  'material-close-circle': 'error',
  'material-alert': 'warning',
  'material-alert-outline': 'warning',
  'material-alert-circle': 'warning',
  'material-alert-decagram': 'warning',
  'material-bug': 'seti:bsl',
  'material-bug-outline': 'seti:bsl',
  'material-puzzle': 'puzzle',
  'material-puzzle-outline': 'puzzle',
  'material-comment-question': 'comment-alt',
  'material-comment': 'comment',
  'material-comment-outline': 'comment',
  'material-message': 'comment',
  'material-message-outline': 'comment',
  'material-help': 'comment-alt',
  'material-help-circle': 'comment-alt',
  'material-help-circle-outline': 'comment-alt',
  'material-lightbulb': 'starlight',
  'material-lightbulb-outline': 'starlight',
  'material-bell': 'bars',
  'material-bell-outline': 'bars',
  'material-bookmark': 'bookmark',
  'material-bookmark-outline': 'bookmark',
  'material-flag': 'pennant',
  'material-flag-outline': 'pennant',
  'material-calendar': 'calendar',
  'material-calendar-outline': 'calendar',
  'material-clock': 'seti:clock',
  'material-clock-outline': 'seti:clock',
  'material-clock-fast': 'seti:clock',
  'material-eye': 'preview',
  'material-eye-outline': 'preview',
  'material-eye-off': 'random',
  'material-folder': 'document',
  'material-folder-outline': 'document',
  'material-folder-open': 'open-book',
  'material-file': 'document',
  'material-file-outline': 'document',
  'material-file-document': 'document',
  'material-file-document-outline': 'document',
  'material-file-tree': 'list-format',
  'material-format-list-bulleted': 'list-format',
  'material-format-list-numbered': 'list-format',
  'material-tag': 'pennant',
  'material-tag-outline': 'pennant',
  'material-tag-multiple': 'pennant',
  'material-shield': 'shield',
  'material-shield-outline': 'shield',
  'material-shield-check': 'shield',
  'material-shield-lock': 'shield',
  'material-lock': 'random',
  'material-lock-outline': 'random',
  'material-key': 'random',
  'material-key-variant': 'random',
  'material-arrow-right': 'right-arrow',
  'material-arrow-right-bold': 'right-arrow',
  'material-arrow-left': 'left-arrow',
  'material-arrow-up': 'up-arrow',
  'material-arrow-down': 'down-arrow',
  'material-chevron-right': 'right-arrow',
  'material-chevron-left': 'left-arrow',
  'material-chevron-up': 'up-caret',
  'material-chevron-down': 'down-caret',
  'material-menu': 'bars',
  'material-dots-horizontal': 'bars',
  'material-dots-vertical': 'bars',
  'material-plus': 'add-document',
  'material-plus-circle': 'add-document',
  'material-minus': 'minus',
  'material-trash-can': 'trash',
  'material-trash-can-outline': 'trash',
  'material-delete': 'trash',
  'material-content-copy': 'copy',
  'material-clipboard': 'copy',
  'material-clipboard-text': 'copy',
  'material-share': 'forward-slash',
  'material-share-variant': 'forward-slash',
  'material-export': 'forward-slash',
  'material-import': 'cloud-download',
  'material-refresh': 'random',
  'material-reload': 'random',
  'material-cached': 'random',
  'material-sync': 'random',
  'material-undo': 'left-arrow',
  'material-redo': 'right-arrow',
  'material-home': 'starlight',
  'material-home-outline': 'starlight',
  'material-cart': 'document',
  'material-package': 'seti:npm',
  'material-package-variant': 'seti:npm',
  'material-database': 'seti:db',
  'material-database-outline': 'seti:db',
  'material-server': 'seti:terraform',
  'material-server-network': 'seti:terraform',
  'material-cloud': 'cloud-download',
  'material-cloud-outline': 'cloud-download',
  'material-image': 'preview',
  'material-image-outline': 'preview',
  'material-camera': 'preview',
  'material-video': 'preview',
  'material-volume-high': 'starlight',
  'material-volume-low': 'starlight',
  'material-volume-off': 'starlight',
  'material-headphones': 'starlight',
  'material-microphone': 'starlight',
  'material-monitor': 'preview',
  'material-cellphone': 'preview',
  'material-laptop': 'preview',
  'material-keyboard': 'preview',
  'material-mouse': 'preview',
  'material-printer': 'preview',
  'material-cloud-print': 'preview',
  'material-translate': 'translate',
  'material-account-group': 'user',
  'material-google-translate': 'translate',
  'material-web': 'external',
  'material-earth': 'external',
  'material-currency-usd': 'document',
  'material-currency-eur': 'document',
  'material-credit-card': 'document',
  'material-thumb-up': 'approve-check',
  'material-thumb-up-outline': 'approve-check',
  'material-thumb-down': 'close',
  'material-thumb-down-outline': 'close',
  'material-emoticon-happy': 'starlight',
  'material-emoticon-sad': 'starlight',
  'material-emoticon-cool': 'starlight',
  'material-fire': 'warning',
  'material-water': 'starlight',
  'material-leaf': 'starlight',
  'material-flash': 'sun',
  'material-weather-sunny': 'sun',
  'material-weather-night': 'moon',
  'material-weather-partly-cloudy': 'cloud-download',
  'material-brightness-7': 'sun',
  'material-brightness-4': 'moon',
  'material-brightness-auto': 'sun',
  'material-theme-light-dark': 'sun',
  'material-cog-transfer': 'setting',
  'material-toolbox': 'starlight',
  'material-hammer-wrench': 'starlight',
  'material-wrench': 'starlight',
  'material-hammer': 'starlight',
  'material-broom': 'starlight',
  'material-shovel': 'starlight',
  'material-test-tube': 'starlight',
  'material-flask': 'starlight',
  'material-flask-outline': 'starlight',
  'material-school': 'document',
  'material-graduation-cap': 'document',
  'material-clipboard-check': 'approve-check',
  'material-progress-check': 'approve-check',
  'material-account-tie': 'user',
  'material-card-account-details': 'user',
  'material-account-key': 'user',

  // --- Material — programming / tech logos (use Starlight tech icons) ---
  'material-language-python': 'seti:python',
  'material-language-javascript': 'seti:javascript',
  'material-language-typescript': 'seti:typescript',
  'material-language-go': 'seti:go',
  'material-language-rust': 'seti:rust',
  'material-language-ruby': 'seti:ruby',
  'material-language-php': 'seti:php',
  'material-language-html5': 'seti:html',
  'material-language-css3': 'seti:css',
  'material-language-c': 'seti:c',
  'material-language-cpp': 'seti:cpp',
  'material-language-csharp': 'seti:c-sharp',
  'material-language-java': 'seti:java',
  'material-language-kotlin': 'seti:kotlin',
  'material-language-swift': 'seti:swift',
  'material-language-r': 'seti:r',
  'material-nodejs': 'seti:notebook',
  'material-npm': 'seti:npm',
  'material-yarn': 'seti:yarn',
  'material-react': 'seti:react',
  'material-vuejs': 'seti:vue',
  'material-angular': 'seti:angular',
  'material-docker': 'seti:docker',
  'material-kubernetes': 'seti:kubernetes',
  'material-git': 'seti:git',
  'material-github': 'github',
  'material-gitlab': 'gitlab',
  'material-bitbucket': 'bitbucket',

  // --- FontAwesome — brands (social icons) ---
  'fontawesome-brands-github': 'github',
  'fontawesome-brands-github-alt': 'github',
  'fontawesome-brands-gitlab': 'gitlab',
  'fontawesome-brands-bitbucket': 'bitbucket',
  'fontawesome-brands-discord': 'discord',
  'fontawesome-brands-twitter': 'twitter',
  'fontawesome-brands-x-twitter': 'x.com',
  'fontawesome-brands-mastodon': 'mastodon',
  'fontawesome-brands-youtube': 'youtube',
  'fontawesome-brands-twitch': 'twitch',
  'fontawesome-brands-linkedin': 'linkedin',
  'fontawesome-brands-linkedin-in': 'linkedin',
  'fontawesome-brands-instagram': 'instagram',
  'fontawesome-brands-facebook': 'facebook',
  'fontawesome-brands-threads': 'threads',
  'fontawesome-brands-reddit': 'reddit',
  'fontawesome-brands-stack-overflow': 'stackOverflow',
  'fontawesome-brands-medium': 'medium',
  'fontawesome-brands-dev': 'devTo',
  'fontawesome-brands-patreon': 'patreon',
  'fontawesome-brands-npm': 'seti:npm',
  'fontawesome-brands-python': 'seti:python',
  'fontawesome-brands-docker': 'seti:docker',
  'fontawesome-brands-slack': 'slack',
  'fontawesome-brands-telegram': 'telegram',
  'fontawesome-brands-whatsapp': 'whatsapp',
  'fontawesome-brands-html5': 'seti:html',
  'fontawesome-brands-css3': 'seti:css',
  'fontawesome-brands-js': 'seti:javascript',
  'fontawesome-brands-react': 'seti:react',
  'fontawesome-brands-vuejs': 'seti:vue',
  'fontawesome-brands-angular': 'seti:angular',
  'fontawesome-brands-aws': 'seti:terraform',
  'fontawesome-brands-google': 'starlight',
  'fontawesome-brands-microsoft': 'starlight',
  'fontawesome-brands-apple': 'starlight',
  'fontawesome-brands-android': 'starlight',
  'fontawesome-brands-linux': 'seti:terraform',
  'fontawesome-brands-ubuntu': 'seti:terraform',
  'fontawesome-brands-chrome': 'starlight',
  'fontawesome-brands-firefox': 'starlight',

  // --- FontAwesome — solid (UI) ---
  'fontawesome-solid-house': 'starlight',
  'fontawesome-solid-user': 'user',
  'fontawesome-solid-cog': 'setting',
  'fontawesome-solid-gear': 'setting',
  'fontawesome-solid-magnifying-glass': 'magnifier',
  'fontawesome-solid-search': 'magnifier',
  'fontawesome-solid-rocket': 'rocket',
  'fontawesome-solid-star': 'star',
  'fontawesome-solid-heart': 'heart',
  'fontawesome-solid-bookmark': 'bookmark',
  'fontawesome-solid-tag': 'pennant',
  'fontawesome-solid-flag': 'pennant',
  'fontawesome-solid-bell': 'bars',
  'fontawesome-solid-envelope': 'email',
  'fontawesome-solid-comment': 'comment',
  'fontawesome-solid-info-circle': 'information',
  'fontawesome-solid-circle-info': 'information',
  'fontawesome-solid-check': 'approve-check',
  'fontawesome-solid-check-circle': 'approve-check-circle',
  'fontawesome-solid-circle-check': 'approve-check-circle',
  'fontawesome-solid-times': 'close',
  'fontawesome-solid-xmark': 'close',
  'fontawesome-solid-circle-xmark': 'error',
  'fontawesome-solid-triangle-exclamation': 'warning',
  'fontawesome-solid-exclamation-triangle': 'warning',
  'fontawesome-solid-question-circle': 'comment-alt',
  'fontawesome-solid-circle-question': 'comment-alt',
  'fontawesome-solid-arrow-right': 'right-arrow',
  'fontawesome-solid-arrow-left': 'left-arrow',
  'fontawesome-solid-arrow-up': 'up-arrow',
  'fontawesome-solid-arrow-down': 'down-arrow',
  'fontawesome-solid-bars': 'bars',
  'fontawesome-solid-plus': 'add-document',
  'fontawesome-solid-minus': 'minus',
  'fontawesome-solid-trash': 'trash',
  'fontawesome-solid-pen': 'pencil',
  'fontawesome-solid-pencil': 'pencil',
  'fontawesome-solid-copy': 'copy',
  'fontawesome-solid-share': 'forward-slash',
  'fontawesome-solid-download': 'cloud-download',
  'fontawesome-solid-upload': 'cloud-upload',
  'fontawesome-solid-cloud': 'cloud-download',
  'fontawesome-solid-lock': 'random',
  'fontawesome-solid-key': 'random',
  'fontawesome-solid-shield': 'shield',
  'fontawesome-solid-shield-halved': 'shield',
  'fontawesome-solid-eye': 'preview',
  'fontawesome-solid-eye-slash': 'random',
  'fontawesome-solid-book': 'open-book',
  'fontawesome-solid-book-open': 'open-book',
  'fontawesome-solid-file': 'document',
  'fontawesome-solid-folder': 'document',
  'fontawesome-solid-rss': 'rss',
  'fontawesome-solid-calendar': 'calendar',
  'fontawesome-solid-clock': 'seti:clock',
  'fontawesome-solid-fire': 'warning',
  'fontawesome-solid-bolt': 'sun',
  'fontawesome-solid-sun': 'sun',
  'fontawesome-solid-moon': 'moon',

  // --- Octicons (GitHub) ---
  'octicons-mark-github': 'github',
  'octicons-mark-github-16': 'github',
  'octicons-mark-github-24': 'github',
  'octicons-rocket': 'rocket',
  'octicons-rocket-16': 'rocket',
  'octicons-rocket-24': 'rocket',
  'octicons-book': 'document',
  'octicons-book-16': 'document',
  'octicons-book-24': 'document',
  'octicons-repo': 'document',
  'octicons-repo-16': 'document',
  'octicons-issue-opened': 'comment-alt',
  'octicons-issue-opened-16': 'comment-alt',
  'octicons-issue-closed': 'approve-check-circle',
  'octicons-git-pull-request': 'forward-slash',
  'octicons-git-merge': 'forward-slash',
  'octicons-git-branch': 'forward-slash',
  'octicons-git-commit': 'forward-slash',
  'octicons-tag': 'pennant',
  'octicons-tag-16': 'pennant',
  'octicons-star': 'star',
  'octicons-star-16': 'star',
  'octicons-star-24': 'star',
  'octicons-heart': 'heart',
  'octicons-heart-16': 'heart',
  'octicons-bell': 'bars',
  'octicons-bell-16': 'bars',
  'octicons-search': 'magnifier',
  'octicons-search-16': 'magnifier',
  'octicons-gear': 'setting',
  'octicons-gear-16': 'setting',
  'octicons-eye': 'preview',
  'octicons-eye-16': 'preview',
  'octicons-info': 'information',
  'octicons-info-16': 'information',
  'octicons-alert': 'warning',
  'octicons-alert-16': 'warning',
  'octicons-alert-24': 'warning',
  'octicons-bug': 'seti:bsl',
  'octicons-check': 'approve-check',
  'octicons-check-16': 'approve-check',
  'octicons-check-circle': 'approve-check-circle',
  'octicons-x': 'close',
  'octicons-x-16': 'close',
  'octicons-x-circle': 'error',
  'octicons-arrow-right': 'right-arrow',
  'octicons-arrow-right-24': 'right-arrow',
  'octicons-arrow-left': 'left-arrow',
  'octicons-arrow-up': 'up-arrow',
  'octicons-arrow-down': 'down-arrow',
  'octicons-chevron-right': 'right-arrow',
  'octicons-chevron-left': 'left-arrow',
  'octicons-chevron-up': 'up-caret',
  'octicons-chevron-down': 'down-caret',
  'octicons-three-bars': 'bars',
  'octicons-three-bars-16': 'bars',
  'octicons-kebab-horizontal': 'bars',
  'octicons-plus': 'add-document',
  'octicons-plus-16': 'add-document',
  'octicons-trash': 'trash',
  'octicons-pencil': 'pencil',
  'octicons-copy': 'copy',
  'octicons-link': 'external',
  'octicons-link-external': 'external',
  'octicons-cloud': 'cloud-download',
  'octicons-cloud-download': 'cloud-download',
  'octicons-cloud-upload': 'cloud-upload',
  'octicons-download': 'cloud-download',
  'octicons-upload': 'cloud-upload',
  'octicons-package': 'seti:npm',
  'octicons-database': 'seti:db',
  'octicons-server': 'seti:terraform',
  'octicons-shield': 'shield',
  'octicons-lock': 'random',
  'octicons-key': 'random',
  'octicons-zap': 'sun',
  'octicons-fire': 'warning',
  'octicons-rss': 'rss',
  'octicons-mail': 'email',
  'octicons-comment': 'comment',
  'octicons-comment-discussion': 'comment',
  'octicons-people': 'user',
  'octicons-person': 'user',
  'octicons-organization': 'user',
  'octicons-clock': 'seti:clock',
  'octicons-calendar': 'calendar',
  'octicons-bookmark': 'bookmark',
  'octicons-flag': 'pennant',
  'octicons-light-bulb': 'starlight',
  'octicons-paper-airplane': 'forward-slash',
  'octicons-rocket-ship': 'rocket',

  // --- Simple Icons (brand vocabulary) ---
  'simple-github': 'github',
  'simple-gitlab': 'gitlab',
  'simple-bitbucket': 'bitbucket',
  'simple-discord': 'discord',
  'simple-twitter': 'twitter',
  'simple-x': 'x.com',
  'simple-mastodon': 'mastodon',
  'simple-linkedin': 'linkedin',
  'simple-youtube': 'youtube',
  'simple-twitch': 'twitch',
  'simple-instagram': 'instagram',
  'simple-facebook': 'facebook',
  'simple-reddit': 'reddit',
  'simple-stackoverflow': 'stackOverflow',
  'simple-medium': 'medium',
  'simple-dev': 'devTo',
  'simple-patreon': 'patreon',
  'simple-npm': 'seti:npm',
  'simple-python': 'seti:python',
  'simple-javascript': 'seti:javascript',
  'simple-typescript': 'seti:typescript',
  'simple-react': 'seti:react',
  'simple-vuedotjs': 'seti:vue',
  'simple-angular': 'seti:angular',
  'simple-go': 'seti:go',
  'simple-rust': 'seti:rust',
  'simple-ruby': 'seti:ruby',
  'simple-php': 'seti:php',
  'simple-html5': 'seti:html',
  'simple-css3': 'seti:css',
  'simple-docker': 'seti:docker',
  'simple-kubernetes': 'seti:kubernetes',
  'simple-git': 'seti:git',
  'simple-slack': 'slack',
  'simple-mailchimp': 'email',
  'simple-rss': 'rss',
};

export const ICON_SET_PREFIXES = [
  'material',
  'fontawesome',
  'octicons',
  'simple',
  'lucide',
] as const;

export type IconSet = (typeof ICON_SET_PREFIXES)[number];
